feat: support css module
max-team/json-mirror-compiler pull request #20
Opened 2022-04-27 15:26 UTC by hqqxxf

2022-04-28 05:31 UTC, Sheetaa requested changes

2022-04-28 05:31 UTC, Sheetaa commented on src/__tests__/compiler-js.test.ts
> +        expect(result.code.js).toContain("@baidu/cosmic-ui-search");
不应该和 legoId 强绑定，也不应该写死@baidu/cosmic-ui-search，不够通用

2022-04-28 05:31 UTC, Sheetaa commented on src/js/CodeBuffer.ts
> +                if (toPath[toPath.length - 1] === 'styles') {
针对 styles 的处理不要写死，传参数控制可以对什么字段进行什么处理

2022-04-28 05:31 UTC, Sheetaa commented on src/__tests__/compiler-js.test.ts
> +    it('css module预置', () => {
名字改为：外观定制：变体

2022-04-28 05:31 UTC, Sheetaa commented on src/__tests__/compiler-js.test.ts
> +    it('css module定制', () => {
名字改为：外观定制：预制

2022-05-03 10:31 UTC, Sheetaa approved these changes

2022-05-03 10:31 UTC, merged

2022-09-10 16:14 UTC, meixg commented on src/js/CodeBuffer.ts
> +Object.assign(process, ${JSON.stringify(this.afterProcess ? this.afterProcess : {})});
现在不管设不设置 afterProcess，都要生成出来一个 Object.assign。
应该判断一下，没有 afterProcess 的时候就不要有 Object.assign 了

2022-09-10 16:18 UTC, meixg commented
在产出的 process 函数上附加属性，这个功能真的有必要增加在这个库里面么？编译阶段自己在后面拼接更加合理吧。

另外 `afterProcess` 这个设置项的名称起的非常有问题，只看这个名字，完全不能理解是要做什么。类似 `attachData` 这种表含义的名称更加合理一些。